export type NewsItem = {
  title: string;
  link: string;
  description: string;
  pubDate: string;
  source: string;
  sourceUrl: string;
};

// Generated by the weekly content workflow. The live /api/news feed remains the primary source.
export const newsSnapshot: NewsItem[] = [
  {
    title:
      'BIR Makati launches MS-TAMP to assist micro, small taxpayers - manilatimes.net',
    link: 'https://news.google.com/rss/articles/CBMiuwFBVV95cUxPczNHcTFRX0NWNk9OYjE1alUzNHVlbk4zNmpJRldDanc4S3k2bmtlc0JydEItNHZvWFd5YzJ4N0VlTTJzWGZpX1pCa3NqNXJLdEZBZU9tVE5SazQxVGpWYVlSdG16c2ZJVmVfenhTUnUwaWsyTUxfMmJpcXA0ajNxZEViT0gxNVZUX1NpaVFJakxmYXdPY0ROaVdtZ1lrZXAxQ3hscnk5LVdjaml0aXA1TnZGNDMxWXlJM0VB0gHAAUFVX3lxTE5CM2phcmxTUkFIYmprUlNvdS1ZQ1dSbUhlY2l1VUNnMlRkcFhWYkF0SlBFT28xNUxEWXI5V1U2MWgya2dqdXhNaElLZThUZTJIYkpEMEdwOGVIdkN2ejZKRzF3WFNnczhSb1dsYlUtU1BxdTlSaHNWaGFXRzQyWlA1V0V3QVlpdTJLVE9vYjU1RTY1Q2xuejFKVFJmYlNIVl94T1V6NUZMUk1PZ1F2dWJ5SHl5SWF3UndtVW1fLTNQMw?oc=5',
    description:
      'BIR Makati launches MS-TAMP to assist micro, small taxpayers &nbsp;&nbsp; manilatimes.net',
    pubDate: 'Sun, 20 Sep 2026 23:41:08 GMT',
    source: 'manilatimes.net',
    sourceUrl: 'https://www.manilatimes.net',
  },
  {
    title:
      '2 Makati drivers’ licenses suspended for firetruck obstruction - Philstar.com',
    link: 'https://news.google.com/rss/articles/CBMirAFBVV95cUxQMjZnTmF4SDd3MV9jbC1kUC1vYVRLTGJXNmg1X3JwR1NzNTQtNkFMbndJTVJLcDJ6MTQwc1A2V0dJVC1CS3VQSm5zVWVrSU9xcHZSc2M0ZVZocGp6Z01jYS04dUd0V0VGT0FoX21xQldrR2JuWEdJOXNpTFo2bWNSejhPQ2NTM3k4enlvNzZjcTJHc0lGSldDcjlTNzMtOGhBcjlYa3c3SzJFRFBZ0gGzAUFVX3lxTE03WVoyYVV6bFkwT3JlMk5ScHJMM3NEWjJTR18tTkRaLUxwanJJbktaQUdIcUdSNEF3VnljdERhOTdMcjdLVnZHSHJsUmtIdHBWMmlrd1FkUGo5WF9XLXl6NW5rcG5Ra0JJWGd5ZENjNlNzZzBPMnR3dmwtWEFlTTVxLXNBQ0xnTHJTdFZKUDJMRUx4cngwYm01bHpKX29qeGl5WXBfQklDZHU1LVhZUno4S2JZ?oc=5',
    description:
      '2 Makati drivers’ licenses suspended for firetruck obstruction &nbsp;&nbsp; Philstar.com',
    pubDate: 'Sun, 20 Sep 2026 16:00:00 GMT',
    source: 'Philstar.com',
    sourceUrl: 'https://www.philstar.com',
  },
  {
    title:
      'Coffee Plz 2026 Brings the Coffee Community Together in Makati - lofficielph.com',
    link: 'https://news.google.com/rss/articles/CBMic0FVX3lxTE1qdXJreHBiRzN1ZVctaExnanh6SVpRT0pMaV9HY1pLMTZmaVI5bnVaMHF2cWhjOGdUbWk5aTZhemN1R2dVUkVtdXdjYXJEeF91ZUFSdzF2a2I1VmYzNGtLNTdYSWNuajRnUG1rdm82YVBtZzA?oc=5',
    description:
      'Coffee Plz 2026 Brings the Coffee Community Together in Makati &nbsp;&nbsp; lofficielph.com',
    pubDate: 'Sat, 19 Sep 2026 23:00:25 GMT',
    source: 'lofficielph.com',
    sourceUrl: 'https://www.lofficielph.com',
  },
  {
    title:
      'LTO suspends licenses of two Makati drivers who blocked fire trucks - tribune.net.ph',
    link: 'https://news.google.com/rss/articles/CBMiowFBVV95cUxPZXdTYXNSb0xmUlFTZkM2NmtHLU5pbjcwYmZRZ0Ffc3U0alh1V1YyeWRVM1E5ZnNZV1dsa3psbjNjYm5jODdoYnpldGFaamQ5Y3VRQVc4Yk5uUE9adFZaSVp4NXNUNmlHU05Kb2tQdlZ2S2JwWThoRFVjZHhRZ0xjUEM0eVVXTFQ0OHJQa1FWdXgwR0dMRlplRnRKODFSVWlJX0Ew?oc=5',
    description:
      'LTO suspends licenses of two Makati drivers who blocked fire trucks &nbsp;&nbsp; tribune.net.ph',
    pubDate: 'Sat, 19 Sep 2026 09:28:38 GMT',
    source: 'tribune.net.ph',
    sourceUrl: 'https://tribune.net.ph',
  },
  {
    title:
      'Odd Cafe in Makati City: A Quirky and Pet-friendly Cafe - Philippine Primer',
    link: 'https://news.google.com/rss/articles/CBMifEFVX3lxTFBLaWRtdnRfbTFYTVh5eEF1T1dBS2RWd1ZWay04VnZXdms4dFNKTmZOMzd0eVlnVEpRU05GSzJXUVVzZGQzUU0zSnctVGI5NGtROUl4cEQ5NnBBZmI5WFBmTXMtdEFYbGI0dDFIaWNuZjNHUTQ3ZjlTblFLRGI?oc=5',
    description:
      'Odd Cafe in Makati City: A Quirky and Pet-friendly Cafe &nbsp;&nbsp; Philippine Primer',
    pubDate: 'Sat, 19 Sep 2026 03:45:00 GMT',
    source: 'Philippine Primer',
    sourceUrl: 'https://primer.com.ph',
  },
  {
    title:
      'Looking for art classes in Makati? ARTa welcomes learners of all levels - ABS-CBN',
    link: 'https://news.google.com/rss/articles/CBMizgFBVV95cUxQbnc0dXA2V3dncms0VVptaXNiOGpyRjNPSjZCTTZUc09KRndEbUd6NlR0RTFubUdQYlRoVWVVNHNpdDFaMlV4ejNreURvRkNsN1RaalZOM1VUTVN4RTJDdVhCVDhabFZ4WU4tR0VFQnFabWtxQkZVRS1MRmY4dFdpdVlhblQ3djZOYzJXbnBtVWt5R050czRXTkY5SGNULWszNUlad0NFc1g0OGg1WWdQckZmeGttMUJSeEN4ZGlQTG5fbl91d1BNaVpkajdqdw?oc=5',
    description:
      'Looking for art classes in Makati? ARTa welcomes learners of all levels &nbsp;&nbsp; ABS-CBN',
    pubDate: 'Fri, 18 Sep 2026 09:56:48 GMT',
    source: 'ABS-CBN',
    sourceUrl: 'https://www.abs-cbn.com',
  },
  {
    title:
      'Makati police: Online posts on rising crime fake news - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMiiAFBVV95cUxPdHdRMThIaDdJbFY5QmxWV3NUb1VSSHQ0MVNhU0lLZlh5M0JTT2hGOENsTFpjUTJKX0tDZy1nSTMyaGdVVzg4dmdOeTBxZ1dzTUVpaTdmajZpWHc5MXhqS2pGYy1HMGpLZGZjQkxUZkFNY0t0RzNCNWRCQjBkWlRnOHp4aEpMZm9G?oc=5',
    description:
      'Makati police: Online posts on rising crime fake news &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Fri, 18 Sep 2026 04:07:45 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title:
      'Pinay tennis champ Alex Eala visited her former school, Colegio San Agustin–Makati, for a quick tennis practice on the courts where her passion for the sport was “nurtured, supported, and encouraged.” Eala poses for a photo with school officials. (Courtesy: C - facebook.com',
    link: 'https://news.google.com/rss/articles/CBMi1wFBVV95cUxOSmdjMXBPelVYcFB5TjdTR2xxVjRBTUtoU2Flb01xZHVJa2E1VnFIc05tNDROeC10U1hJOFpuQXU2M0hyNWl3RXBnam42ZURTMnRCTjIySmgzOF9YMXBuNlh0MEJZM3RZdEZnaTdYUm1rVXl0ZDBWNkQ5cE1jVFZyVUsxcERVTXlPYWE5RGxKbDkzMXR1Q2Fqcm5LQlQ3OHV2X3JnQWFMTlNaSnJzLWI0WGZsUEZ0ZWdHRGQwbngzTkY0cHZZSVUyYWJfckpQSDM0VURqNXNvbw?oc=5',
    description:
      'Pinay tennis champ Alex Eala visited her former school, Colegio San Agustin–Makati, for a quick tennis practice on the courts where her passion for the sport was “nurtured, supported, and encouraged.” Eala poses for a photo with school officials. (Courtesy: C &nbsp;&nbsp; facebook.com',
    pubDate: 'Thu, 17 Sep 2026 23:46:04 GMT',
    source: 'facebook.com',
    sourceUrl: 'https://www.facebook.com',
  },
  {
    title: '2 Makati pizzerias among 100 best worldwide - Philstar.com',
    link: 'https://news.google.com/rss/articles/CBMimgFBVV95cUxOZ1VWUVg5VFBfRllJZWdhaW5PWVdqUXNTaV9UUG9mUnpqNDZsdUxFQkFRcHFsNHY5eHJGOE9uMlNpOVM1SnZiOWJLUDN1eVFNQUtqTzBBNmh5NWFJLURXM250RHIwc016T1RfeHE5SC1ETnA3aGVUbHlDT3NpdjJTMkFkR3B1R3F0QWZsMk9JaUppY1VtX2VnUGdB0gGgAUFVX3lxTE9RallXZEhYbUEyZTlwblBuMk0zVzZpeTh2UTRGZGliRjhGVndyNFJlY3FOVDc4dlh5ODBvcTNzenlraTJ4cENCRk4zRWw1ZFdoQWxnMEttTnAtb0puajZIakJzUWVQbE9IdnVGd1AzdTZXZ3o1ZU43ZGJMY0E3YzdkUkc3YzVGbFZKQ2x2TjJLNWF6VEVmYWNqMkNOSmV1dEY?oc=5',
    description:
      '2 Makati pizzerias among 100 best worldwide &nbsp;&nbsp; Philstar.com',
    pubDate: 'Thu, 17 Sep 2026 16:00:00 GMT',
    source: 'Philstar.com',
    sourceUrl: 'https://www.philstar.com',
  },
  {
    title:
      'Alex Eala pays a visit to alma mater Colegio San Agustin Makati - GMA Network',
    link: 'https://news.google.com/rss/articles/CBMixwFBVV95cUxQSllaRTBQeWI1S29Eb1I0Ym5XWS1MT1B6Qk5BaDZMT2NWOXkteVg2Q25INkppSmp2Sm91S1VUcGZCYU16aHVsTlF1dzdwRVdudUh3T0RWc052UTV3R2xnNExpUV9HOG14MnFCeG9rdUU2LTBDMllpUWViYlRVTFB3cFltZjhnTjU2ZDQxZ0trZW0tTHZvZXdKQ3oyZHVkbzBIcElNRWRhWmtxZnlIWm5YV0ZiSDhVX2hwSW1YWTg4Nk5oNkNHUE530gHMAUFVX3lxTE9qMkFNbE1jTkRVajluNllreGFzbmM4cC15YmFkR0NPSHFxWHN1YzRpVVZTT3hsZDRsZVdRQXJNZnNGVmNxSkp5czUtZ1hJRTVoN1hvNlBJR1pkNzJaMWhsUW54MjdHUURHbDJ6Nzh5dlRnLXRRYzNxbU5rLWFzUnNUVEhwM2pEand1SUdablJBM2xDd250NHlxWVZKMWRUZHFWRWFRLVZoenZPWXVrRWFIRkM4UmdDMGJDZWMwYzN4emtjaDlLN29ZczJKTw?oc=5',
    description:
      'Alex Eala pays a visit to alma mater Colegio San Agustin Makati &nbsp;&nbsp; GMA Network',
    pubDate: 'Thu, 17 Sep 2026 02:57:04 GMT',
    source: 'GMA Network',
    sourceUrl: 'https://www.gmanetwork.com',
  },
  {
    title:
      'NBI: Siblings nabbed in Makati over fake notary services - Inquirer.net',
    link: 'https://news.google.com/rss/articles/CBMimAFBVV95cUxPbmRleVkzR3BpX0ViRU5JNFlrNHZFSFMxUHN2ZGNhSkYtU05DZ0pKUU5iaDdzOGx0SUNHX1J1anNmcGdtOVRlUGhqWE5hZTNPZXl1S3ZIMl9uTTJNaXBPS0c3LVRtVzM4VHoxTFVWblk5Y0hxbHVyQnhaU1U2VWl1Rm0yY25MTzJ4OGc1OUpFZ3VXWkV6bm04ONIBngFBVV95cUxQVnp2eHk3eXoyU1NFY3I0YjVkNmZUX0dncFlUcnpFbWxDakpISXo4YjhXOFE0ejdmbDA5d05SUHBBM1JCQ2cwU1JVSzBCOUZLVDhvejJOVHFCcDAyOE56RzNndFNCWmt4VG5xTWVqZkVlQ01JWG1IUkU5UkNHWUZWZDZRWXpsd3FIS0NBa2JwNzRjTUJLTmtLdXk2anNKdw?oc=5',
    description:
      'NBI: Siblings nabbed in Makati over fake notary services &nbsp;&nbsp; Inquirer.net',
    pubDate: 'Wed, 16 Sep 2026 09:08:00 GMT',
    source: 'Inquirer.net',
    sourceUrl: 'https://newsinfo.inquirer.net',
  },
  {
    title: 'Fairmont Makati joins global Move for Wishes campaign - ABS-CBN',
    link: 'https://news.google.com/rss/articles/CBMiwgFBVV95cUxPMUVqS3RxbDVWUnk1VnJvR0JXMTVxdDgwRzJRajFiZ1RBTXR0cTVDcnVKMGtEelprdU1faU5PcDY2aTZ3SmdaTE81NXVYT2duQkFzYzlFNWR4Q08taGpDV1Q4eVhtQmZoTkQyQ2d1SWlXX1hha3lJdUNFVTRRV3ZEYXg3SDRrZjJiU2F3Skh2LWlUb3VCaHc2REQ3bTc3MXBSeVkyZjhmbnhLeXRfaUVKTVZhSlVaOUNQamszb2d4a1YwZw?oc=5',
    description:
      'Fairmont Makati joins global Move for Wishes campaign &nbsp;&nbsp; ABS-CBN',
    pubDate: 'Wed, 16 Sep 2026 08:05:59 GMT',
    source: 'ABS-CBN',
    sourceUrl: 'https://www.abs-cbn.com',
  },
  {
    title: '2 men nabbed over Makati building signage theft - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMiggFBVV95cUxNSFhPaVlMSkx4aTJfWklsVDRmd3h1QTVydFFfQW5mM0hFMU44R0R1d3FJZ2lpYnZ6cFNoZkxHX2RnOGgwLVN1czEydjJMN2xIRnZYd2RaV0J0VUZLS21LdXlZM1dEcVctT0hxNHVhSHFLNmxiWmc0LTljOG9RYUF1Mkdn?oc=5',
    description:
      '2 men nabbed over Makati building signage theft &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Wed, 16 Sep 2026 07:41:38 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title:
      'How engineering shapes Makati’s ultra-luxury landmark - tribune.net.ph',
    link: 'https://news.google.com/rss/articles/CBMijwFBVV95cUxON0lfWnFPaU9iczhTNHBRZGxpbXBTWTRKVV9SWXN6QURrM3VGM3p0SGloN1EzRmd6eTNSZzNhaWEyZVREcDRtRnRsOVA5R3A2TUZyVGd4N2cyaFN5THAzRGpjR2xJa0ZJUWdpeTJsbUhHOFFRUzlyVFRIMGFwb3R0SExrZjVFWnpnenpud1pOdw?oc=5',
    description:
      'How engineering shapes Makati’s ultra-luxury landmark &nbsp;&nbsp; tribune.net.ph',
    pubDate: 'Tue, 15 Sep 2026 21:22:46 GMT',
    source: 'tribune.net.ph',
    sourceUrl: 'https://tribune.net.ph',
  },
  {
    title:
      "One Fortis Plaza: A Transit-Oriented Office Development in Makati's Next Business Hub - dmcihomes.com",
    link: 'https://news.google.com/rss/articles/CBMiwgFBVV95cUxNZXBsT1k5bFlxOGFpZWlJT1A5VmFPcHlFbHFqYW02aFN4bUZRUjNjTURaMjZBNlNCOG9wQURTal9McUg1MlptM29lSTRuYnFBRlZpV2tUZm9LS3VtZ1hBSUdGSGpiVFAyc293YV8wVXM2aHBsd01mcjBLV0YwZjhZYlNiQlktaW55RDBDdVpoaHZMc2NQU3p6VmEwTGZRcFNIaE1rMDBUX21BbHF6RElYM01RZG9QeHpLQkFFZElUYXFWZw?oc=5',
    description:
      "One Fortis Plaza: A Transit-Oriented Office Development in Makati's Next Business Hub &nbsp;&nbsp; dmcihomes.com",
    pubDate: 'Tue, 15 Sep 2026 01:59:04 GMT',
    source: 'dmcihomes.com',
    sourceUrl: 'https://www.dmcihomes.com',
  },
  {
    title:
      'Philip Morris adds jobs in Makati as Philippines hub scales up global AI role - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMiqgFBVV95cUxQeVg1TnFIdVVndnhmMVpVQUtucEhFc1F5RTV1ZkQ1V0IwaVBzU1JOaXZjRTJaMnowb0xGNUZoOEsycVlBT180VXVCQWNFbFI0TjJrazB0aS1tZUk1TzNLaTRVQXp5cThtaXd5M2RVR0NCbHpramZxY0pCOHZ5YzlKSV9vNTdYelFJV3VyRThncVZCUDlnbHVoVk5Jc1RhRlduR2xlbDdSWlFpZw?oc=5',
    description:
      'Philip Morris adds jobs in Makati as Philippines hub scales up global AI role &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Mon, 14 Sep 2026 21:25:15 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title:
      'Philip Morris’ multi-services unit expands Makati operations - manilatimes.net',
    link: 'https://news.google.com/rss/articles/CBMixwFBVV95cUxQSzFpQUhHNmtUMEYxaVQzdlNsRzdXVEkwOEdWTnpEQWxlMGt1SENpcWk5VnJidEVYX2lvWjFwTGRZSlN1Z2IyUGNKOFVud21ya29ocnYtSlJpaEhKRi1uejRxVmFaOC1ZZkxIVW5qR1BBa2ROTmFqdmZfbEY5U1FjSzdrT2pYNHk1aTRvV0RKcVIwNjdBem5oajVZMnE4RmlhX0F2dmxIVzIwWkZXMXozcHFETE1acFM1XzEweVJXOWstSmVydTBr?oc=5',
    description:
      'Philip Morris’ multi-services unit expands Makati operations &nbsp;&nbsp; manilatimes.net',
    pubDate: 'Mon, 14 Sep 2026 16:11:00 GMT',
    source: 'manilatimes.net',
    sourceUrl: 'https://www.manilatimes.net',
  },
  {
    title: 'PMIBS unveils expansion site in Makati - businessmirror.com.ph',
    link: 'https://news.google.com/rss/articles/CBMihwFBVV95cUxOVXU3TkVRS19ZNWNwNG5QbGhqYVMtTkdDSEdyMUptdjFkVm95X1BKczd4aEE1b1J4NnN3Njh6eUhBY3BJYlNrNElyUEZHMmtrOXhEUmlDWmd3MEI4SDN6OEtMak82T1RjNlhtek80bDMxUVF2S3BmdHJ5d3liUE9UMHNDaXptNWM?oc=5',
    description:
      'PMIBS unveils expansion site in Makati &nbsp;&nbsp; businessmirror.com.ph',
    pubDate: 'Mon, 14 Sep 2026 12:52:51 GMT',
    source: 'businessmirror.com.ph',
    sourceUrl: 'https://businessmirror.com.ph',
  },
  {
    title: 'Elite runners Muge, Magtubo rule 10 Miler Makati leg - GMA Network',
    link: 'https://news.google.com/rss/articles/CBMiuAFBVV95cUxNUHRtRmRUYnZQekliVERwc3Z6S3dITy1Db1dyVnNrUXJfZ2FRNW50TU5TeFVmUHFSOXlQZ3F4RUYxYTBQMzJmbjltWjZvTGl0TFFVSFU2c0N0RGs2MVJRQ1dVQ0xCSmk2ejNoNUI1bDVHWXhtTVpLR1YtY0g4MU1PTEZ1LURzSXo3QzBDTWhvNzdNNlJPd0JrVHkzRTctdF9ua0o2R0d0VGlFUk42aXAzVTV0QlkzaXRs?oc=5',
    description:
      'Elite runners Muge, Magtubo rule 10 Miler Makati leg &nbsp;&nbsp; GMA Network',
    pubDate: 'Mon, 14 Sep 2026 06:33:15 GMT',
    source: 'GMA Network',
    sourceUrl: 'https://www.gmanetwork.com',
  },
  {
    title:
      'Makati buy-bust: 4 drug suspects caught after motorcycle crash - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMilAFBVV95cUxOUG1PUm9RaTFVUGtJX3FSWWt6ZWtwY2V0cUNBelJKZS0zU3BVaDlHTl9xSTRSLVF3Zmo5dDNqNEozQndpcGtWdmIycjVZRUNiZjR0VEZnWEhjVFQyZ1RjSHFrRkVKbEhSUmRHRm9lcTM1QmZvYVNyaTc4dmlHNnhqVTZEUHhFN0doc25tQWxLR3RZZk04?oc=5',
    description:
      'Makati buy-bust: 4 drug suspects caught after motorcycle crash &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Sat, 12 Sep 2026 07:00:00 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title: 'Makati: The city that is learning to walk again - Inquirer.net',
    link: 'https://news.google.com/rss/articles/CBMiiwFBVV95cUxQWjJoSllRNjJkNGV2N2hOeVlCZjBfV0U2YmJwV2h5QXI3YkNuMnFYX2V1RWZONHVCZUxJQzVnQmZPb2s3SE84cklEeHBVX1FOZ1ZfZ1dCSEx6WVFKWGsxQzd0TUV6LWRNMW9fZktrU2UxalRmam9KeEphNndIYkFkNU1oeWtHNUZ3SW000gGQAUFVX3lxTE1QOEpUVEF6Sm9od0EwcmtSQXQwQU54Z05SMTJOY21sQk1tTDNrdlRhVTVxSEVPdG9aM2hiSVBobUhYcDRFd2pmY29zZFZxbVo0aXppN1IyTWF5ejZkRDN1LXBYQ1pFbmV5Q3NUS0ttZkpGanZZVHcwVzZEU0puWDBETTFXVzNfLUNoc3pzcXIyOA?oc=5',
    description:
      'Makati: The city that is learning to walk again &nbsp;&nbsp; Inquirer.net',
    pubDate: 'Fri, 11 Sep 2026 13:56:00 GMT',
    source: 'Inquirer.net',
    sourceUrl: 'https://business.inquirer.net',
  },
  {
    title:
      'The prestige, privilege and livability of Makati CBD - Inquirer.net',
    link: 'https://news.google.com/rss/articles/CBMikgFBVV95cUxOMnNVQ1ptMFNYR3V1c1ItcUpqXzRudDJJQjBONHhDR3FtME1lSXFJTE5oQlFnaUgxd3ZmcjlkckVzWHZ2bDNHMlZxaGlNell4OF9QeVBhX2tjMmJLZEhFQk9jRjlXaUZ6ZWhBaXotckIzMTFIY2dGc29tYWFvc05aRGZZU1owbF9xUzU1SHlwZFd3QdIBlwFBVV95cUxNRUFtb25iV05CQ0YybVp3REFxU25ienBoSUVTRGVWcmc2b1NzdExMR09pR2JQV3pwTVFIV3hxYjU0UUJOanNVR1ItOENNaE9UdVdxd3c3dnh1M3praHRZSmdrZWlUbDZrcUhERkxMV1V2ZWk2MGxscVhTOGFwQXAwbnViU2FXMzNGMHA3ME1WOG81WVkxc1VV?oc=5',
    description:
      'The prestige, privilege and livability of Makati CBD &nbsp;&nbsp; Inquirer.net',
    pubDate: 'Fri, 11 Sep 2026 07:00:00 GMT',
    source: 'Inquirer.net',
    sourceUrl: 'https://business.inquirer.net',
  },
  {
    title:
      'Man arrested after trying to steal telecom property in Makati - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMilAFBVV95cUxNTEpYUWJlVnRkSVpUV0lKeUZ4OGRuWFg5WExTcE5hTGRGT010S013VVFhVDl5NWtNRTlOaDRMM3NGd1RqN1BGRW1jQmNxLXYwWTNOaW9jc2FKc0x1QjFfQkFPRXExWXJPYzNidXJLc0xTSHFZUWFSMmZELUhyaU82Qjc3b0JPSUpQSlRiZHFqdk5lTzNH?oc=5',
    description:
      'Man arrested after trying to steal telecom property in Makati &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Thu, 10 Sep 2026 07:00:00 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title:
      '2 nabbed over theft of Makati surveillance equipment - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMikwFBVV95cUxNQmh1eEgtT2pNMzFFbjc4NWJtVzZjX1EwTTNGMkQ5aHkzTHIwNEV3UTJLUWwxdERJalNCeHFKY3NTY0p2WUdNUzEzRkJrZjFlUmc2RlhVU05Obmdqa2Fzb1VKd2RId0pzWTR0QjhMcVB1YVUwdDllc25UTDNoeW9oSGlJRkFZaTFUNFZJdXBMYmdvWnc?oc=5',
    description:
      '2 nabbed over theft of Makati surveillance equipment &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Tue, 08 Sep 2026 07:00:00 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title: '14,000 secure jobs, career support in Makati - Manila Bulletin',
    link: 'https://news.google.com/rss/articles/CBMie0FVX3lxTFB4YVQzbVotcWZKeERNSHl1MWNuamJLckpSSFVOM2NYN3pnZ0laMjJ1VzR2VEFjdmt3U29Oc1NRLTUwbElySTEzaG5NTld5VFhJUWpxSEFWSjBtOHJuMEpkck55blJ4b3BXRUVJZkR0aF90VGdGdmR1LWp4NA?oc=5',
    description:
      '14,000 secure jobs, career support in Makati &nbsp;&nbsp; Manila Bulletin',
    pubDate: 'Tue, 08 Sep 2026 07:00:00 GMT',
    source: 'Manila Bulletin',
    sourceUrl: 'https://mb.com.ph',
  },
  {
    title:
      'Makati employment programs support 14,000 jobseekers, workers - tribune.net.ph',
    link: 'https://news.google.com/rss/articles/CBMimAFBVV95cUxPWGkybk1pLXlfYmZpaFZ4UU9kTmNqLThEd3d6T2tOREl3TnBKYWZ6dFlYblRudG1LbTdyNU1UTklxRVpnX0lQcFdzRnc1bC1qTUl0dFg2S0lYbnJQbnV3UFV4ZkNFazJjQk4tNFktSE55Z2RMYjZMWWdlY3BheThIY0JzcVhEZ0x1MVFJbV9BWGF5TlY0WUdZWA?oc=5',
    description:
      'Makati employment programs support 14,000 jobseekers, workers &nbsp;&nbsp; tribune.net.ph',
    pubDate: 'Tue, 08 Sep 2026 07:00:00 GMT',
    source: 'tribune.net.ph',
    sourceUrl: 'https://tribune.net.ph',
  },
  {
    title: 'Makati Business Club backs Pax Silica project - manilatimes.net',
    link: 'https://news.google.com/rss/articles/CBMitAFBVV95cUxPN0pLX2wxS2pacjZ0b3dxeEp4RTRJYzN6c21mMGRVa1Q0TVg3ejF5LTJUNDBNMDVZbV9VT3RFbU1ZdzZCb3hRNnl0ZEllRTE3TS0xSFN3bzhQdndJbDBNTnJvUWxEUG9QR1pjVkl3T1ByWEt4Z1lBX2xtZVRkZzQyUDNtQklrV191TDR0NWd4SVZGM0Q0Y0k5YWo3ZDNPZEg1TWpKbHV3UlZXRnEwOEZRM0hlNmjSAboBQVVfeXFMT0JSOWI4eE1XVkVEVGZuc2RCcndGbUl5OWRnX09EZ0t0RmhkdHBxZC1BVmUtMXVGOU5FYk16dmdaU2RmVHVuTGRua1VCZWNLSWpsUmp1WlJPX2k1U2gtQUd5dTUtVXRGX28tTmJBeWlDX2tDMk5WRnBQQUhGeXZJM2VILUF0cnUtcnBBNlotVGdOc1M3V0M1RnVrc0lyU0JuSGpRdHlNRFJEVW9nN3dLSHJVQ2lmcHhiNVFn?oc=5',
    description:
      'Makati Business Club backs Pax Silica project &nbsp;&nbsp; manilatimes.net',
    pubDate: 'Mon, 07 Sep 2026 07:00:00 GMT',
    source: 'manilatimes.net',
    sourceUrl: 'https://www.manilatimes.net',
  },
  {
    title:
      'Makati eats: Mirèio elevates Sunday brunch with fresh truffles - ABS-CBN',
    link: 'https://news.google.com/rss/articles/CBMivgFBVV95cUxPMWJOeDdsTHFrV0s3M2Vzb2RGUnlqdXMyTXJYLTAtbHVmZnlOelBlZngyM1cxS0IzZ0ZabE5hV2ZDM2Q3ZzR2QnlLYlBCNk5qNzU1TXZJV0l3UGdVRksxWmRYNFFQaXVRcU95bC0zR3F5RE9VZkhqRWt4emw0SktHVkc0alFMS1hQcmFORUlvU094NkRNYzc5MnNqNFM2anRuTy04YVFMdVZybkpjRDhnTUtrWmpRSjFncmU1YkxB?oc=5',
    description:
      'Makati eats: Mirèio elevates Sunday brunch with fresh truffles &nbsp;&nbsp; ABS-CBN',
    pubDate: 'Sun, 06 Sep 2026 07:00:00 GMT',
    source: 'ABS-CBN',
    sourceUrl: 'https://www.abs-cbn.com',
  },
  {
    title:
      'BI nabs Korean fugitive involved in fraud, apprehends cohort in Makati - Bureau of Immigration Philippines',
    link: 'https://news.google.com/rss/articles/CBMingFBVV95cUxNYUdVNVVCcHlvRFRpNkwwN0Z4MFJMVDlCaU5aWkNRQWJiUzJYSThiX1JXcTI2RENBVndsTWc3TmhEOHlDV25qcU53Y3Z6YWYzb21uUkJ5eDk5cHcxUHN6MWxjR21JMjB4bWExZXV1MnlXUUxJTVl6SHljWXhhR1RnZmwyYUZuVjB6T2ZRd1lmVUlkQUxlZ3pQUm1hdFJmUQ?oc=5',
    description:
      'BI nabs Korean fugitive involved in fraud, apprehends cohort in Makati &nbsp;&nbsp; Bureau of Immigration Philippines',
    pubDate: 'Sun, 06 Sep 2026 04:22:59 GMT',
    source: 'Bureau of Immigration Philippines',
    sourceUrl: 'https://immigration.gov.ph',
  },
  {
    title:
      'Police nab 2 suspects in Makati City for illegal drugs, gambling - manilatimes.net',
    link: 'https://news.google.com/rss/articles/CBMiwgFBVV95cUxQX3F3eWJCTEk0TDhHSDgzYkVOVEJCVWo5YlRfdlVBX2JmcXM1Vi1OcDNCZ19vS2pxbDhESWpUWGcwRmZNTENYTmxXaWNFVzRKSlBaYW9OWk85RzNhSzlYZXVfaDZMQ3lacXhMbnhhTnVPU0NvZm5aRHI0NmVWZjVKLWNaU2xobUd1Szg3eGpIUFplbkxRTVNTc1NrNExqNmQ2cXVzeGpZWmpCY0VNWXZGdXJxeDNJbVphSjUwUnQxVnB1Z9IBxwFBVV95cUxOblAwRzd2V0lPaWhZSi1RMnlCTlF1S0JzY3BiV05Vd3RoaGpQeUZTRzh5dUhjeFN5b2RXVTU4elR0QVhWcGlaYWtLNWhJVkU0MjRJamtNSk9Da2IyVHlGWGE5UjZyUVlWcXpoLS02T3dKYmNZb0tZV0RvNkhKWVM4Sm5MX3ZQVXY4WnBpMDZSWmdRU2xISUJYZU1xbTNDZ2MwNFhvXzBiNk9OZm9hOFJ5ZmFBOGpxcXFqdVJ6YnlreEFQVHMzeEgw?oc=5',
    description:
      'Police nab 2 suspects in Makati City for illegal drugs, gambling &nbsp;&nbsp; manilatimes.net',
    pubDate: 'Sat, 05 Sep 2026 07:00:00 GMT',
    source: 'manilatimes.net',
    sourceUrl: 'https://www.manilatimes.net',
  },
];
